### ISSUE TITLE
Getting 404 error

### ISSUE THREAD

**Issue by Gunnvant** [longhowlam/ikeaScraper#1]
I ran the script, after a while the script abruptly stopped and gave a 404 error.  Here is the trace:
`INFO [2017-12-11 12:46:19] SEARCH http://www.ikea.com/nl/nl/search/?query=stoel&pageNumber=1
INFO [2017-12-11 12:46:23] npages 44
INFO [2017-12-11 12:46:23] loop over pages
INFO [2017-12-11 12:47:22] search page 1 processed
INFO [2017-12-11 12:48:29] search page 2 processed
INFO [2017-12-11 12:49:26] search page 3 processed
Error in open.connection(x, "rb") : HTTP error 404.`

I am using windows 10. Also when I check the image directory, I see images that seem corrupt or not downloaded completely.

Can you please help?

**Comment by longhowlam** [comment]
I think IKEA might have blocked your requests.

**Comment by Gunnvant** [comment]
Any workaround this? When you wrote the scrapper, did you have a privileged access?

**Comment by longhowlam** [comment]
No, i did not have privileged access, I did the scraping during the IKEA hackaton, now that the hackaton is over and my hackaton app is finished and I released the code maybe they don like it when too many people scrape....?

**Comment by Gunnvant** [comment]
Ok, sure. Will figure out something. Thanks.
